### ISSUE TITLE
ETA or roadmap for an official release of this module?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/geophp#2]
Hello, and thanks for porting this module to Backdrop CMS :)  I'm going to be using it on two of my Backdrop sites in the near future, and would love for it to have a stable release. Do you have a roadmap for issues preventing a stable release? I'd love to help get it across the finish line :)

See also: 
* https://github.com/backdrop-contrib/geofield/issues/2
* https://github.com/backdrop-contrib/geocoder/issues/5

**Comment by stpaultim** [comment]
See: https://github.com/backdrop-contrib/geofield/issues/2

**Comment by laryn** [comment]
Do I understand correctly that this module/library is wrapped into `geofield` and not necessary?

**Comment by laryn** [comment]
Oh, I was just trying to enable `geocoder` and it looks like this is still a dependency for that module. Is this module ready for a release?

**Comment by jenlampton** [comment]
It could be that the dependancy wasn't removed. Maybe try to comment it out
and see if it still works?

>

**Comment by laryn** [comment]
@jenlampton See if this makes sense to you:
https://github.com/backdrop-contrib/geocoder/issues/18

**Comment by stpaultim** [comment]
@jenlampton and @laryn - For the record, Geophp is still listed as a dependency for the Geocoder module. I'm about to test it without GeoPHP and will see how it works. 

Update: I removed the GeoPHP dependency for Geocoder and tried to use it. I got this error message when trying to create a new node with an addressfield and geofield:

`Error: Call to undefined function geophp_load() in geocoder_cache_get() (line 314 of /var/www/triplo/maps/simplo/src/modules/contrib/geocoder/geocoder.module).`

I then restored the dependency and enabled the GeoPHP module and was able to create a location node without error.

**Comment by stpaultim** [comment]
Ah, I see that there are updates to the Geocoder module that are not in the current release. I'll try the dev module.

**Comment by jenlampton** [comment]
Maybe it's time for a new release of geocoder?

**Comment by stpaultim** [comment]
Yes, the dev version of GeoCoder worked without GeoPHP!

@jenlampton
