### ISSUE TITLE
Remove gifad from Maintainers?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/geophp#3]
@klonos writes on Zulip:

>  the user gifad no longer exists on GitHub. For security reasons perhaps remove them from the list of maintainers (someone may claim that username and potentially do harm if they request to be added)? ...we could add their name in the "Credits" section, and link to https://www.drupal.org/u/gifad instead.

**Comment by jenlampton** [comment]
The current GitHub user created their account on [on August 7, 2023](https://github.com/gifad?tab=overview&from=2023-08-01&to=2023-08-31). If that is the same person, I expect gifad may appear in this queue letting us know. But for now I think it would be wise to remove them as a maintainer until we get a specific request. 

See d400aaf
